Add Coverage Badge
lirantal/express-version-route pull request #43
Opened 2019-06-27 06:32 UTC by DrFaust92

2019-06-27 08:00 UTC, DrFaust92 commented
Resolves #43

2019-06-27 08:00 UTC, DrFaust92 commented
I had trouble so there are many junk commits, needs to be squashed.

2019-06-28 08:44 UTC, lirantal commented
No worries. Looking good! Thanks a bunch 🙏❤️

Seems you forgot to add the codecov badge to the README? :-)

2019-06-28 08:45 UTC, lirantal requested changes

2019-06-28 08:45 UTC, lirantal commented on README.md
> -[![Dependency Status](https://david-dm.org/lirantal/express-version-route.svg)](https://david-dm.org/lirantal/express-version-route)
Missed adding the codecov badge :)

2019-06-29 13:35 UTC, lirantal commented
Thanks @DrFaust92 👌

2019-06-29 13:36 UTC, merged

2019-06-29 13:38 UTC, lirantal commented
:tada: This PR is included in version 1.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/express-version-route)
- [GitHub release](https://github.com/lirantal/express-version-route/releases/tag/v1.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: